permalink: none
layout: default
base_dir: '/documentation'
ga_id: UA-305465-18
google_search_api_key: ABQIAAAAwQSx00E3x6cE8SZwCh4n4xQq-OkhIxd_ZE7aAH0uHNhzy7T8tRQVXkr0B0EDPTlKRUyVD-g3QczVOg
google_search_site_url: http://dedomenon.github.com/documentation
